gitserver: gitserver
query-runner: query-runner
repo-updater: repo-updater
searcher: searcher
replacer: replacer
symbols: ./cmd/symbols/build.sh execute
github-proxy: github-proxy
frontend: env CONFIGURATION_MODE=server SITE_CONFIG_ESCAPE_HATCH_PATH=$HOME/.sourcegraph/site-config.json frontend
watch: ./dev/changewatch.sh
nginx: nginx -p . -g 'daemon off;' -c $PWD/dev/nginx.conf 2>&1 | grep -v 'could not open error log file'
web: ./node_modules/.bin/gulp --color watch
syntect_server: ./dev/syntect_server
zoekt-indexserver-0: ./dev/zoekt/wrapper indexserver 0
zoekt-indexserver-1: ./dev/zoekt/wrapper indexserver 1
zoekt-webserver-0: ./dev/zoekt/wrapper webserver 0
zoekt-webserver-1: ./dev/zoekt/wrapper webserver 1
keycloak: ./dev/auth-provider/keycloak.sh
docsite: ./dev/docsite.sh -config doc/docsite.json serve -http=localhost:5080
lsif-server: yarn --cwd lsif run run:server
lsif-worker: yarn --cwd lsif run run:worker
prometheus: ./dev/prometheus.sh
grafana: ./dev/grafana.sh
postgres_exporter: ./dev/postgres_exporter.sh
# jaeger: docker run --name=jaeger --rm -p5775:5775/udp -p6831:6831/udp -p6832:6832/udp -p5778:5778 -p16686:16686 -p14268:14268 jaegertracing/all-in-one:latest



# docker run --name jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 -p 9411:9411 jaegertracing/all-in-one:1.17
